CREATE TABLE IF NOT EXISTS user
(
    id_user   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_user VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id_user)
);

ALTER TABLE user
    ADD CONSTRAINT uc_user_email UNIQUE (email);

CREATE TABLE IF NOT EXISTS categories
(
    id_category BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id_category)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);