CREATE TABLE if not exists users
(
    id_user   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_user VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id_user),
    CONSTRAINT uc_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id_category BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id_category)
);
--
-- CREATE TABLE if NOT EXISTS location
-- (
--     id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     longitude FLOAT,
--     latitude  FLOAT,
--     CONSTRAINT pk_location PRIMARY KEY (id)
-- );

CREATE TABLE if not exists events
(
    id_event           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         TEXT                                    NOT NULL,
    id_cat             BIGINT                                  NOT NULL,
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description        TEXT                                    NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id_initiator       BIGINT                                  NOT NULL,
    location_latitude  FLOAT,
    location_longitude FLOAT,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  BIGINT                                  NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                 NOT NULL,
    state              VARCHAR(255),
    title              VARCHAR(120)                            NOT NULL,
    views              BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id_event),
    CONSTRAINT FK_EVENTS_ON_ID_CAT FOREIGN KEY (id_cat) REFERENCES categories (id_category),
    CONSTRAINT FK_EVENTS_ON_ID_INITIATOR FOREIGN KEY (id_initiator) REFERENCES users (id_user)
);

CREATE TABLE if not exists compilations
(
    id_compilations BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned          BOOLEAN                                 NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id_compilations)
);

CREATE TABLE if not exists events_compilations
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_evecom_on_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id_compilations),
    CONSTRAINT fk_evecom_on_event FOREIGN KEY (event_id) REFERENCES events (id_event)
);

CREATE TABLE If NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE,
    event_id     BIGINT,
    requester_id BIGINT,
    status       VARCHAR(255),
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT FK_REQUESTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id_event),
    CONSTRAINT FK_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id_user)
);
